// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aijobwikxttiwshznrqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpam9id2lreHR0aXdzaHpucnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5OTcxNjgsImV4cCI6MjA5NDU3MzE2OH0.D6nSfFpN0exhoctqq5D-k23z9UjeQmQfBsX9y5fx3GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);