// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zcfgfrlbomtghxsakzvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjZmdmcmxib210Z2h4c2FrenZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NzAwMzUsImV4cCI6MjA5NDM0NjAzNX0.07zeH2ZulO_JPv2xMznI-wvcJOzswvYtzNqUa4pimwo";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);